version: "3.9"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: test_docker
      MYSQL_USER: souliya
      MYSQL_PASSWORD: 1111
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork

  api:
    build: ./backend/
    ports:
      - "3030:3030"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ''
      DB_DATABASE: db_ecommerce
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge